### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by jijibn** [mitiku1/Emopy-CapsNet#1]
Hello ;
could you please provide the dataset

**Comment by ymitiku** [comment]
@jijibn you can find ck+ dataset [here](http://www.consortium.ri.cmu.edu/ckagree/). The other dataset I used is from kaggle [fer2013](https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data) dataset.

**Comment by jijibn** [comment]
thanks a bunch
